[Ad-Urls]
Hagezi = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt
#Hagezi = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/multi-onlydomains.txt
#Adguard = https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
#Oisd = https://small.oisd.nl/domainswild2
#Hagezi_Pro = https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro-onlydomains.txt
#Hagezi_Pro_Plus = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt
#Hagezi_TIF_Medium = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.medium-onlydomains.txt
Hagezi_TIF_Mini = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.mini-onlydomains.txt
#Hagezi_TIF = https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif-onlydomains.txt
Hagezi_DoH_VPN = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass-onlydomains.txt
#Oisd_NSFW = https://nsfw-small.oisd.nl/domainswild2
Hagezi_Fake = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake-onlydomains.txt
#Pop-Up Ads = https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads-onlydomains.txt
#Microsoft = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice-onlydomains.txt
#Tiktok = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok-onlydomains.txt
#Tiktok = https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended-onlydomains.txt
